-- MRP Outsourcing Orders Table
CREATE TABLE IF NOT EXISTS `llx_mrpoutsourcing_order` (
    `rowid`             INT(11)         NOT NULL AUTO_INCREMENT,
    `fk_mo`             INT(11)         NOT NULL COMMENT 'Link to llx_mrp_mo.rowid',
    `fk_supplier`       INT(11)         NOT NULL COMMENT 'Link to llx_societe.rowid (supplier)',
    `supplier_email`    VARCHAR(255)    NOT NULL,
    `status`            VARCHAR(32)     NOT NULL DEFAULT 'draft' COMMENT 'draft|sent|confirmed|done|cancelled',
    `reduce_stock`      TINYINT(1)      NOT NULL DEFAULT 0,
    `stock_reduced`     TINYINT(1)      NOT NULL DEFAULT 0,
    `token`             VARCHAR(64)     NOT NULL,
    `date_send`         DATETIME        DEFAULT NULL,
    `date_confirmed`    DATETIME        DEFAULT NULL,
    `date_done`         DATETIME        DEFAULT NULL,
    `supplier_ref`      VARCHAR(128)    DEFAULT NULL,
    `note_private`      TEXT            DEFAULT NULL,
    `note_public`       TEXT            DEFAULT NULL,
    `mail_log`          MEDIUMTEXT      DEFAULT NULL,
    `callback_log`      MEDIUMTEXT      DEFAULT NULL,
    `date_creation`     DATETIME        NOT NULL,
    `fk_user_creat`     INT(11)         DEFAULT NULL,
    `date_modification` DATETIME        DEFAULT NULL,
    `fk_user_modif`     INT(11)         DEFAULT NULL,
    `import_key`        VARCHAR(14)     DEFAULT NULL,
    `entity`            INT(11)         NOT NULL DEFAULT 1,
    PRIMARY KEY (`rowid`),
    KEY `idx_mrpoutsourcing_fk_mo` (`fk_mo`),
    KEY `idx_mrpoutsourcing_token` (`token`),
    KEY `idx_mrpoutsourcing_status` (`status`),
    CONSTRAINT `fk_mrpoutsourcing_mo` FOREIGN KEY (`fk_mo`) REFERENCES `llx_mrp_mo` (`rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
